### ISSUE TITLE
EPUB's scrollToId is not working

### ISSUE THREAD

**Issue by mmenu-mantano** [readium/r2-streamer-swift#107]
Example book: Wasteland

The `scrollToId` function in `utils.js` is not working at all.

Here's a working implementation:

```js
function scrollToId(id) {
    var element = document.getElementById(id);
    if (!element) {
        return;
    }
    element.scrollIntoView();
    
    if (!isScrollModeEnabled()) {
        var currentOffset = window.scrollX;
        var pageWidth = window.innerWidth;
        // Adds half a page to make sure we don't snap to the previous page.
        document.body.scrollLeft = snapOffset(currentOffset + (pageWidth / 2));
    }
}
```

**Comment by JayPanoz** [comment]
Just as a heads-up in case `utils.js` is meant to be used on Android, you might want to be cautious with scroll + `body` as I can remember fixing awful issues cross platform because of that (Webkit/Safari vs. Blink/Chrome + Gecko/FF). 

I had to switch to `document​.scrolling​Element | document.body` (cf. https://developer.mozilla.org/en-US/docs/Web/API/document/scrollingElement) to get something consistent at some point.

**Comment by mmenu-mantano** [comment]
There's a `utils.js` on Android too, but they have diverged significantly now. I think it's using mostly `document.scrollingElement` on Android but `document.body` on iOS. Do you recommend that we switch to `(document​.scrolling​Element | document.body)` in place of `document.body` on Swift?

**Comment by JayPanoz** [comment]
Sounds like a good idea to use it if it doesn’t create issues.

It was indeed meant to take care of all the idiosyncrasies (including quirks mode) and is supported as of iOS 9 ([caniuse](https://caniuse.com/#feat=document-scrollingelement)) so you could even save the `|| document.body` (sorry double pipe it should have been) part if a very quick test with `document.scrollingElement` works as expected.

**Comment by mmenu-mantano** [comment]
Alright, I will take a look when fixing the `scrollWithId`. 👍

**Comment by JayPanoz** [comment]
For the record, just took a quick look in Safari and Chrome – mind you, WebViews may differ but I’m not expecting they do in this case. 

```
// Safari
document.scrollingElement
→ body (so document.body)

// Chrome
document.scrollingElement
→ html (so document.documentElement)
```

**Comment by aferditamuriqi** [comment]
just read this conversation here, 

I had lots of issues with body, and moved all to scrollingElement a while ago and it works perfectly as expected,
