### ISSUE TITLE
`Loggable` protocol have 2 functions duplicated as `static`

### ISSUE THREAD

**Issue by ghost** [readium/r2-streamer-swift#13]
This is done in order to be able to call them in `initializers` before the call of `super.init()`.
There must be a better way to solve this.

**Comment by frank-actialuna** [comment]
Maybe not the most elegant way to solve this issue, but you can declare an empty struct conforming to the `Loggable` protocol inside your `init`, and instantiate it when you want to log before `super.init()` is called.

    func init() {
      if (failure) {
        struct Logger: Loggable {}
        Logger().log(level:.error, "whatever")
        return nil
      }
      super.init()
    }

**Comment by camill-a** [comment]
Clever, but still a hack, don't know if we will find another solution though. Changing everything is still a possibility

**Comment by mmenu-mantano** [comment]
I think we can close this, it's not a big issue and it doesn't look like we're going to fix this.
