### ISSUE TITLE
Need to add ! in two files

### ISSUE THREAD

**Issue by Jokez80** [readium/r2-streamer-swift#147]
When you import r2streamer you need to go into 
EPUBParser row 199 and and add a ! here: data: smilDataOptional! 
Same with PDFParser on row 195: data: optionalData!

It would be good not to have to do this everytime you do pod update/install

**Comment by mickael-menu** [comment]
I'm pretty sure it's caused by using the Swift 4 compiler.
Which version of Xcode are you using to build the app?

**Comment by Jokez80** [comment]
I have 11.3.1 but usually I build the app with IntelliJ since we are using Flutter.

**Comment by Jokez80** [comment]
We do Pod install when we are trying to build our app with codemagic and as of now we can´t do this because of this issue. So its urgent! @mickael-menu

**Comment by mickael-menu** [comment]
There's not much we can do, R2 requires Swift 5, and your build issue is caused by using Swift 4. You have to check your tools.

Here's the particular feature of Swift 5 we're using in this case: https://github.com/apple/swift-evolution/blob/master/proposals/0230-flatten-optional-try.md

PS: We're an open source community and support is handled graciously by contributors, please be mindful of that when writing.

**Comment by Jokez80** [comment]
> PS: We're an open source community and support is handled graciously by contributors, please be mindful of that when writing.

What was not mindful in my comment? 

Will check if we can use Swift 5 in building on codemagic...

**Comment by mickael-menu** [comment]
> What was not mindful in my comment?

This:

> So its urgent! @mickael-menu

**Comment by Jokez80** [comment]
> So its urgent! @mickael-menu

Well it was urgent to get a respond so we could try to solve it. Either by a change in the code or something else as you so kindly suggested here.

For reference if someone come here in the future with Flutter/Readium issues:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      **config.build_settings['SWIFT_VERSION'] = '5.1.4'**
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

Made it work in IntelliJ.
