### ISSUE TITLE
Xcode cannot find libxml2

### ISSUE THREAD

**Issue by jeffgilbert** [readium/r2-streamer-swift#151]
I'm trying to add readium to a Swift project using Xcode 11.3.1. I've added the following two lines to my Podfile

```
  pod 'R2Navigator', :git => 'https://github.com/readium/r2-navigator-swift.git'
  pod 'R2Streamer', :git => 'https://github.com/readium/r2-streamer-swift.git'
```

When I build the project I get the following error:

R2Streamer Group
Swift Compiler Error Group
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/libxml2/libxml/HTMLparser.h:15:10: 'libxml/xmlversion.h' file not found
Could not build Objective-C module 'libxml2'

How can I get the pod for R2Streamer to find the libxml2 header?

Thanks,
Jeff

**Comment by mickael-menu** [comment]
Hi,

You need to add `$(SDKROOT)/usr/include/libxml2` to the "Header Search Paths" build setting of your project.

**Comment by jeffgilbert** [comment]
Thanks!

I looked in the Build Settings for the app after installing the two pods and it already includes `$(SDKROOT)/usr/include/libxml2`.

I checked the Build Settings for the R2Streamer target in the Pods project, and it was missing `$(SDKROOT)/usr/include/libxml2`. I added it there and it is building. I gather I'll have to re-add that if the pods are ever updated.

Does the Podfile for the R2Streamer pod need to be updated to include that addition to the header search path?

**Comment by mickael-menu** [comment]
I'm not sure actually, I'm only using Carthage.

@aferditamuriqi should know more about the CocoaPods config.

**Comment by jeffgilbert** [comment]
It looks like this has been fixed in another fork maintained by @aferditamuriqi (and is not an issue when using Carthage to integrate, instead of CocoaPods).

**Comment by mickael-menu** [comment]
I'll keep this opened for now as we still need to fix the issue in this repo.

**Comment by aferditamuriqi** [comment]
I’ll be pushing a PR soon for this fix

**Comment by mickael-menu** [comment]
Thanks Aferdita, there's also this issue about the Podspec if you want to take a look: https://github.com/readium/r2-streamer-swift/issues/156#issuecomment-600271740

**Comment by aferditamuriqi** [comment]
@mickael-menu I've added my comment to the mentioned issue, there isn't an issue in the Podspec about GCDWebServer.

**Comment by mickael-menu** [comment]
> @mickael-menu I've added my comment to the mentioned issue, there isn't an issue in the Podspec about GCDWebServer.

Okay I see, thanks

**Comment by mickael-menu** [comment]
CocoaPods is not supported anymore by Readium 2.
