### ISSUE TITLE
Remove percent-encoding (URL encoding) when parsing NCX toc

### ISSUE THREAD

**Issue by ryan-w** [readium/r2-streamer-swift#152]
When the src attribute of the content element in a ncx file has a percent-encoded value, the navigator will not navigate to the link/locator.

Specifically, the ePUB file I’m working with has a `%20` in place of a space.

Example:
`<content src="First%20Chapter.xhtml" />`

Suggested Change:
https://github.com/readium/r2-streamer-swift/blob/630d8953cbad98fb229233caa9d98b2ce16474b3/r2-streamer-swift/Parser/EPUB/NCXParser.swift#L72

`href: element.firstChild(xpath: "ncx:content")?.attr("src").removingPercentEncoding,`

Reference:
https://developer.apple.com/documentation/foundation/nsstring/1409569-removingpercentencoding

**Comment by mickael-menu** [comment]
Thanks for reporting this issue, I'm closing this one because another one reports the same problem but has a sample publication to test. You can follow it here: https://github.com/readium/r2-testapp-swift/issues/320

**Comment by ryan-w** [comment]
Note that the OPF Parser is using the `removingPercentEncoding`.
https://github.com/readium/r2-streamer-swift/blob/630d8953cbad98fb229233caa9d98b2ce16474b3/r2-streamer-swift/Parser/EPUB/OPFParser.swift#L186
