### ISSUE TITLE
crash trying to instantiate PublicationServer

### ISSUE THREAD

**Issue by jeffgilbert** [readium/r2-streamer-swift#156]
In my app, when I try to instantiate a `PublicationServer`, e.g.

```
let publicationServer = PublicationServer()
```

I get a crash while the initializer is trying to `addSpecialResourcesHandlers` for fonts. Deep inside, it fails in `GCDWebServer` at `addHandlerWithMatchBlock` from

```
GWS_DCHECK(_options == nil);
```

`_options` is 
```
{
    BindToLocalhost = 1;
    Port = 61541;
}
```
Is there anything I need to do, or include in the app to create the publication server?

Thanks,
Jeff

**Comment by jeffgilbert** [comment]
After looking at the GCDWebServer docs, it looks like you are supposed to add your handlers before you start the web server. However, in `PublicationServer` it looks like they start the web server and then add the handlers. Should those be reversed?

From PublicationServer.swift:
```
        webServer = GCDWebServer()
        if startWebServer() == false {
            return nil
        }
        addSpecialResourcesHandlers()
```

**Comment by mickael-menu** [comment]
@jeffgilbert Have you tried reversing it in your project to see if it fixes your issue? However, that's surprising that it would work in `r2-testapp-swift` then.

Also, please make sure that you're using the latest `develop` version for the R2 libs.

**Comment by jeffgilbert** [comment]
Thank you for getting back to me.

I was using CocoaPods to integrate R2, but it looks like it has fallen behind the Carthage integration. Notably, when using Carthage to integrate R2 it uses a forked version of GCDWebServer, rather than the original (used by CocoaPods, which is causing the crash). I switched to using Carthage and the crash has been resolved.

I'll mark this issue as closed.

**Comment by aferditamuriqi** [comment]
The original version of GCDWebServer doesn't work with CocoaPods, therefore I had forked it and set up the GCDWebServer to work with both Carthage and CocoaPods. The issue in the original is, that it uses GCDWebServer vs GCDWebServers and it's not compatible to be used in CocoaPods alongside with Carthage, and since we are supporting both, we needed a fix, if you use the original version instead, CocoaPods won't' work,
