### ISSUE TITLE
 The page number display is incorrect.

### ISSUE THREAD

**Issue by nutnuttapon** [readium/r2-streamer-swift#158]
book reflow

**Comment by mickael-menu** [comment]
Hi,

Could you explain more about this issue, with examples?

**Comment by nutnuttapon** [comment]
examples 1 
Click next page 
All 3 pages are number 3.
![Screen Shot 2563-04-15 at 1 31 41 PM](https://user-images.githubusercontent.com/42132959/79305412-904d8500-7f1d-11ea-9293-04fa23a33513.png)
![Screen Shot 2563-04-15 at 1 31 29 PM](https://user-
![Screen Shot 2563-04-15 at 1 31 53 PM](https://user-images.githubusercontent.com/42132959/79305453-9e9ba100-7f1d-11ea-889e-4067753aea04.png)
images.githubusercontent.com/42132959/79305421-93e10c00-7f1d-11ea-84d8-d3256563dc79.png)

**Comment by nutnuttapon** [comment]
example 2 
Currently, on page 13, when pressing the next page Is page 15
![Screen Shot 2563-04-15 at 1 38 26 PM](https://user-images.githubusercontent.com/42132959/79306036-b293d280-7f1e-11ea-847b-8c8621a99560.png)
![Screen Shot 2563-04-15 at 1 38 36 PM](https://user-images.githubusercontent.com/42132959/79306042-b6275980-7f1e-11ea-9b6b-fff8be889013.png)

**Comment by mickael-menu** [comment]
Okay this is the normal behavior.

Unfortunately, we can't have page numbers matching the actual screen pages for reflowable content, because it depends on screen size and user settings.
