### ISSUE TITLE
r2-streamer-swift doesn't build in empty Xcode Swift project

### ISSUE THREAD

**Issue by Trannosaur** [readium/r2-streamer-swift#176]
When I create a new project and I add the r2-streamer-swift pod, I can't build the project. There are a lot of missing types: MediaType, Encryption, EPUBLayout, essentially a bunch of stuff from R2Shared - however I see no issues building R2 shared, and r2shared does seem to be listed as a framework of R2Streamer.

I tried some naive poking around to see if I could fix it (changing swift version from 5 -> 4.2, adding CoreMedia as a framework) but nada.

(devenv: Xcode 14, was defaulted to Swift 5, but tried 4.2 as well, using head of 'develop' branch)

**Comment by mickael-menu** [comment]
Could you share your Podfile or sample project?

**Comment by mickael-menu** [comment]
Closing from lack of activity.

**Comment by Trannosaur** [comment]
Sorry I didn't attach it I should've clarified, I mean a /brand new empty project/ with just the Podfile from README.md so I think my /not thihking/ brain is like oh its built in! HAhahah.

Okay, so I create an empty iOS app project, I use the Podfile snippet from README.md, I run "pod install --repo-update", then I close the project and reopen it as the workspace and ctrl+b and it'll go okay for about 50% of the items and eventually fail when it starts building R2Streamer

Here's the project:

[tersd.zip](https://github.com/readium/r2-streamer-swift/files/5321577/tersd.zip)

(This is now in XCode 12)

**Comment by mickael-menu** [comment]
CocoaPods has been giving us a lot of troubles and [we decided with the team to deprecate its support in Readium last week](https://docs.google.com/document/d/1XkVAThah6uuk7Disj0ONFKqSNGZ3OrQ9fFvo0ZCHrNI/edit). Are you able to use Carthage to integrate R2 instead? We also plan to add support for Swift Package Manager as soon as we secure all the third-party dependencies with it.

**Comment by Trannosaur** [comment]
Ah okay, thanks for the update mate! Appreciate it.
