### ISSUE TITLE
Publication table of contents is empty

### ISSUE THREAD

**Issue by benforsrup** [readium/r2-streamer-swift#197]
Publication.tableOfContents is empty when importing publication. 

Using the develop branch.

**Comment by mickael-menu** [comment]
All tests are passing and I can see the table of contents from the test app. Did you reproduce the problem on the test app?

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-02-24 at 14 34 03](https://user-images.githubusercontent.com/58686775/109008397-92d84980-76ad-11eb-8dcd-a6fdad72b8be.png)
