### ISSUE TITLE
Release 1.2.5 doesn't compile since Xcode 12.5

### ISSUE THREAD

**Issue by vince4** [readium/r2-streamer-swift#203]
Hi,

The last stable release of r2-streamer-swift (1.2.5) doesn't compile since Xcode 12.5.
It's because the version of CryptoSwift used by r2-streamer is not compatible with Xcode 12.5 : 

<img width="1117" alt="Capture d’écran 2021-04-29 à 15 21 02" src="https://user-images.githubusercontent.com/1721591/116557629-e7db4a80-a8fe-11eb-82d1-b4a830f80a3d.png">

Could you please upgrade CryptoSwift version to at least 1.3.2 and make a new release ?

**Comment by mickael-menu** [comment]
@vince4 We have a new 2.0.0 version which is compatible with Xcode 12.5. For now it's only a beta but `2.0.0-beta.2` is pretty stable and used in production by many apps. The final 2.0.0 release will be the next milestone in a couple of weeks.

You can upgrade your app following this migration guide: https://readium.org/mobile/swift/migration-guide

**Comment by vince4** [comment]
Okay, I will try. 
Thank you for your feedback.
