### ISSUE TITLE
Crash when reading Adobe-obfuscated font when publication identifier is empty

### ISSUE THREAD

**Issue by olivierkorner** [readium/r2-streamer-swift#208]
The Adobe font obfuscation algorithm key is built using the publication identifier.

If it is empty, or just `urn:uuid:`, the deobfuscation will crash with a _"Division by zero"_ error because the key is empty:
https://github.com/readium/r2-streamer-swift/blob/4067b31f7e88306d66bcef253b5fb538b7b0be68/r2-streamer-swift/Parser/EPUB/Resource%20Transformers/EPUBDeobfuscator.swift#L69

If the key is empty, the deobfuscator should just return the data with transformation.

I have an EPUB to test the issue that I can send privately but not share here.

**Comment by mickael-menu** [comment]
Thanks Olivier, could you send me the EPUB on Slack?

The toolkit should not crash in this case, but the font won't be deobfuscated. Is it an error in the publication that the font is declared obfuscated, or that the publication identifier is missing?

**Comment by olivierkorner** [comment]
The publication identifier is missing (actually, it is set to `urn:uuid:`. Note that it looks like the font is not obfuscated in the EPUB.
