### ISSUE TITLE
NavDoc & NCX parsing: when to parse which one

### ISSUE THREAD

**Issue by camill-a** [readium/r2-streamer-swift#25]
1. 
Does the NavDoc parsing take precedence over the NCX parsing?
`If NavDoc { parse NavDoc} else { parse NCX}`

2.
Should we consider the EpubVersion for choosing which one to parse?
`If EpubVersion >= 3 { parse NavDoc } else { parse NCX }`

3.
Should we have a "fallback behavior" in case the two documents are present but we didn't found the <toc> in the NavDoc? (Or should it always try to get as much informations as possible in the 2 files if they are present? Though this could add invalid informations from a deprecated NCX document)

*User have an updated NavDoc and a deprecated NCX he forgot*
```
parseNavDoc(to: publication)
if publication.Any {
    parseNcx(to:publication) // Don't overwrite properties already parsed in the NavDoc
                                              // BUT fill the empty ones with the (deprecated?) data from NCX.
}
// OR
parseNavDoc(to: publication)
if publication.toc.isEmpty {
    parseNcx(to:publication) // Only if the TOC could not be found then get the informations
                                              // from the NCX (overwrite?).
}
```

Other points to consider (and probably create other issues):
- Full NCX parsing (`navList`), in order to parse LOA/LOV/LOT/LOI/Landmarks etc..
- In the current WebPubManifest the landmarks section looks like this (in both swift and go):

```
// There is a reference to toc and a file name (in the href). That's not coherent?
  "landmarks" : [
    {
      "href" : "#toc",
      "title" : "Table of Contents"
    },
    {
      "href" : "p10.xhtml",
      "title" : "Begin Reading"
    }
  ],
```

**Comment by banux** [comment]
Hi,

Currently in the go streamer i parse the navigation document first and if i can't populate the TOC i try the NCX. So 1) and 3) i think try to merge the 2 documents will be difficult and not very useful.

**Comment by llemeurfr** [comment]
I think that this process is good: 1) try the nav doc (EPUB3), and if it does not exist or contains no ToC 2) try the NCX (EPUB2). 
This leaves some flexibility if an EPUB3 (by its declared version attribute) contains no nav doc (which is an authoring mistake). 
Doing so also avoids mixing info that may be inconsistent between the nav doc and the ncx, e.g. page lists, landmarks ...
We should create a processing model document to describe such things clearly.

**Comment by HadrienGardeur** [comment]
This should be documented on the main Readium-2 repo in a new document at the following place in the repo: https://github.com/readium/readium-2/tree/master/streamer/parser

**Comment by HadrienGardeur** [comment]
```
// There is a reference to toc and a file name (in the href). That's not coherent?
  "landmarks" : [
    {
      "href" : "#toc",
      "title" : "Table of Contents"
    },
    {
      "href" : "p10.xhtml",
      "title" : "Begin Reading"
    }
  ],
```

We actually fixed self-referencing navigation documents in a recent commit: https://github.com/readium/r2-streamer-go/issues/21

**Comment by camill-a** [comment]
Ok great, will update that on the streamer-swift too.
