### ISSUE TITLE
Special properties in the resources Links

### ISSUE THREAD

**Issue by ghost** [readium/r2-streamer-swift#26]
In the Go version of the streamer, some properties are converted this way (see the contains nested array) :

```
{
    "href": "xhtml/svg-007.xhtml",
    "type": "application/xhtml+xml",
    "properties": {
        "contains": [
            "svg"
        ]
    }
}
```

In the swift streamer the Link's properties are stored in a simple `String` array.

**Comment by gbugniot** [comment]
[Fixed here.](https://github.com/readium/r2-streamer-swift/commit/5588a67aac242e90854d9da0773dabb8edcbc832#diff-d4519de343742659c47b1d1167e8c10aL61)
