### ISSUE TITLE
SmokeTest Epub Test, comparing the streamer output with a reference output

### ISSUE THREAD

**Issue by ghost** [readium/r2-streamer-swift#28]
Add a "Unit(?)" test with the "Smoke Test" epub, generating the associated WebPub manifest and comparing it with the "reference manifest.json".

The reference output is in the R2StreamerTest folder. But must be updated, it's derivated from the Go streamer.

**Comment by danielweck** [comment]
Yes, I would go as far as comparing canonical JSON outputs (similar to LCP license signature verification process).
All R2 "streamer" implementations should match exactly (assuming feature-wise parity).

**Comment by HadrienGardeur** [comment]
Yes, this is something we've discussed before.

I'd like to figure out how we can share those across repos, probably using the main Readium-2 repo.

**Comment by camill-a** [comment]
Yes, this is TBDed precisely, maybe during one of the next readium-2 meeting?

**Comment by mickael-menu** [comment]
Closing this issue as it doesn't look like it will move any time soon.

We need a collective effort to gather test cases in a shared repo, this would be best discussed in [`architecture`](https://github.com/readium/architecture).
