### ISSUE TITLE
Add support for Subtitles

### ISSUE THREAD

**Issue by ghost** [readium/r2-streamer-swift#37]
In EPUB 3.0.x it's possible to indicate that a title is a subtitle:
```xml
<dc:title id="title_2">All About EPUB 3.1</dc:title>
<meta refines="#title_2" property="title-type">subtitle</meta>
<meta refines="#title_2" property="display-seq">2</meta>
```
A recent revision to the Readium Web Publication Manifest also added a subtitle element to play the same role.

We need to add support for subtitles in the streamer, using the same multi-lingual model as the title element.

**Comment by aferditamuriqi** [comment]
@iaomw is this related to the subtitle work you already did? can we close this issue? or is this something different?

**Comment by iaomw** [comment]
Hi, I could say this one is solved. But the situation is more complex. It could have more than one `subtitle`. Maybe, it's necessary to make a bigger change on the data structure. So it could cover all the case with one type. @aferditamuriqi 

For discussion: https://github.com/readium/r2-streamer-swift/pull/43

**Comment by HadrienGardeur** [comment]
A single subtitle is more than enough, I doubt that there are a lot of publications that even have a single subtitle right now.

**Comment by llemeurfr** [comment]
The current code extracts the first subtitle found in the metadata, which is fine for our reference bookseller. Therefore we can close this issue.
