### ISSUE TITLE
RTL Page Progression not supported

### ISSUE THREAD

**Issue by rkwright** [readium/r2-streamer-swift#42]
Open the [EPUB TestSuite 130](http://epubtest.org/epubs/epub30-test-0130-20160116.epub) which is entirely RTL.  Note that the page-progression directive is not honored.  Pages are still laid out LTR.

*Test Environment:*
iPad 5, 16 GB
iOS 11.0.3
R2 Test App 0.2 (2)

**Comment by danielweck** [comment]
@llemeurfr do you mean this? https://github.com/readium/readium-css/tree/develop/docs/i18n-samples/epubs

**Comment by llemeurfr** [comment]
@danielweck yes, plus some extra samples that Jiminy has provided.

**Comment by iaomw** [comment]
As a general issue, it's already solved. So, I will close it. Feel free to reopen it if you think it's necessary.

There are some special cases, I will list them here.
- The html may not containing any language info, it's not accurate using language info from other html files. It might be the mistake by author. One possible solution might be using some NLP API.
- When there are multiple languages, the logic(Jim's document) for primary language is not always correct. That depends on book author.
