### ISSUE TITLE
Table of contents is not parsed for EPUB Test Suite books

### ISSUE THREAD

**Issue by gbugniot** [readium/r2-streamer-swift#45]
When I add test suite books to R2 Reader test app, for example [EPUB Test Suite 150](http://epubtest.org/epubs/epub30-test-0150-20160116.epub), table of contents is not parsed by the streamer.

**Comment by gbugniot** [comment]
Git blaming NavigationDocumentParser.swift, it seems a fix was introduce to resolve an issue with AEXML parser. But with the current version of this lib, I have to remove the previous fix to make it works again.

Please, check this commit: 7cf86a0. Any feedbacks is welcome.

**Comment by gbugniot** [comment]
Somehow, it's related with #44.

**Comment by danielweck** [comment]
For your information, the Readium(1) cloud reader exposes an OPDS feed for the *expanded* epub-testsuite EPUBs located in the IDPF GitHub repository:

https://readium.firebaseapp.com/?epubs=epub_content%2Fepub_testsuite.opds

For example test number `150`:

http://epubtest.org/epubs/epub30-test-0150-20160116.epub
=>
https://github.com/IDPF/epub-testsuite/tree/master/content/30/epub30-test-0150
