### ISSUE TITLE
Handle obfuscated fonts

### ISSUE THREAD

**Issue by olivierkorner** [readium/r2-streamer-swift#5]
Obfuscated font files are currently not deobfuscated by the fetcher.

The fetcher should debobfuscate the font data input stream before passing it to the HTTP server.

Information about which files are obfuscated and which encryption algorithm to use is in the `encryption.xml`file. Two encryption algorithms are possible: Adobe's or IDPF's, though the former is rarely used any more and should be implemented for backward compatibility.

**Comment by rkwright** [comment]
@camill-a   I just tested the R2 Swift Test App with [EPUB Test Suite 103](EPUBTEST 0103 - Font Embedding and Obfuscation Tests:), and the app passed all the tests, so I think this issue can be closed.
