### ISSUE TITLE
TOC doubled elements

### ISSUE THREAD

**Issue by pavelric** [readium/r2-streamer-swift#77]
This happens with this epub [Tanka_RyokufuSanka](https://drive.google.com/open?id=1hCsruGb_mR95nzRQM1upryEJw--Jc6I6)

Screenshot : ![doubledtocios](https://user-images.githubusercontent.com/13640302/48077726-3f921280-e1e8-11e8-8a6e-b8d271f3f3a6.png)

**Comment by JayPanoz** [comment]
Hmmmm, looks like every string is wrapped in a `span` element than is itself wrapped in a `a` element. 

Could it be the reason why every entry is duplicated i.e. at some point `span` was implemented as the primary usage is having a non-linked entry in the TOC (cc @danielweck who raised that issue during a call if I’m not mistaken), but in this case it’s nested in an anchor.

**Comment by mmenu-mantano** [comment]
It seems to be fixed now.

![Simulator Screen Shot - iPhone SE - 2019-05-06 at 20 03 33](https://user-images.githubusercontent.com/6561221/57245028-20aaf680-703a-11e9-9235-cae3bae0e5f7.png)
