### ISSUE TITLE
Parse spine or manifest item Link properties

### ISSUE THREAD

**Issue by olivierkorner** [readium/r2-streamer-swift#9]
Add following native properties (as opposed to and instead of entries in the `properties` property of Link) to Link model for page, spread, layout, orientation et overflow à la classe Link, qui remplace les propriétés `rendition:*` et `page-spread-*`

**Comment by gbugniot** [comment]
[Fixed here.](https://github.com/readium/r2-streamer-swift/commit/5588a67aac242e90854d9da0773dabb8edcbc832#diff-2e9ea8fd0f3105a2993121dea6d7369aR284)
